export const BEGIN_CHECKOUT = 'BEGIN_CHECKOUT';
export const SEND_CART = 'SEND_CART';
export const RECEIVE_CART_SENDING_RESPONSE_NO_ERROR = 'RECEIVE_CART_SENDING_RESPONSE_NO_ERROR';
export const RECEIVE_CART_SENDING_RESPONSE_WITH_ERROR = 'RECEIVE_CART_SENDING_RESPONSE_WITH_ERROR';
export const CANCEL_CHECKOUT = 'CANCEL_CHECKOUT';
export const END_CHECKOUT = 'END_CHECKOUT';
export const RESET_CHECKOUT = 'RESET_CHECKOUT';
