export const BEGIN_CHECKOUT = 'BEGIN_CHECKOUT';
export const SEND_CART = 'SEND_CART';
export const RECEIVE_CART_SENDING_RESPONSE = 'RECEIVE_CART_SENDING_RESPONSE';
export const CANCEL_CHECKOUT = 'CANCEL_CHECKOUT';
export const END_CHECKOUT = 'END_CHECKOUT';
