export const ADD_TRANSACTION_ITEM = 'ADD_TRANSACTION_ITEM';
export const UPDATE_TRANSACTION_ITEM = 'UPDATE_TRANSACTION_ITEM';
export const DELETE_TRANSACTION_ITEM = 'DELETE_TRANSACTION_ITEM';
export const EMPTY_TRANSACTION = 'EMPTY_TRANSACTION';
